en:
  contentDir: content/en-US
  disabled: false
  locale: en-US
  direction: ltr
  label: English
  weight: 1
zh:
  contentDir: content/zh-CN
  disabled: true
  locale: zh-CN
  direction: ltr
  label: 简体中文
  weight: 2
