en:
  contentDir: content/en-US
  disable: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  weight: 1
zh:
  contentDir: content/zh-CN
  disable: true
  languageCode: zh-CN
  languageDirection: ltr
  languageName: 简体中文
  weight: 2
