main:
  # Dropdown menu items after built-in menu items
  - identifier: posts
    name: Posts
    url: /posts
    weight: 1
  - identifier: tags
    name: Tags
    url: /tags
    weight: 2
  - name: Topics
    url: /topics
    weight: 3
